version: "3.9"

services:
 compute_v1:
   restart: always
   image: cybergisx/job_supervisor_v1:34f97bfeadad
   depends_on:
     - redis_v1
   #ports:
   #  - "3000:3000"
   env_file:
     - ./compute_v1.env
   volumes:
     - ./:/job_supervisor
   entrypoint: /bin/bash -c "cd /job_supervisor && ./docker-entrypoint.sh" 
 
 redis_v1:
   restart: always
   image: redis@sha256:69a3ab2516b560690e37197b71bc61ba245aafe4525ebdece1d8a0bc5669e3e2

networks:
  # use pre-existing network
  default:
    name: my-cybergis-compute-network
    external: true
